basePath: /api/v1
definitions:
  model.ExchangeRateReq:
    properties:
      currency-pair:
        type: string
    type: object
host: currency-exchange-g8p8.onrender.com
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is the API for Cadana interview task
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Cadana API
  version: "1.0"
paths:
  /exchange/rates:
    post:
      consumes:
      - application/json
      description: this endpoint gets an exchange rate
      parameters:
      - description: exchange rate request
        in: body
        name: ExchangeRateRequest
        required: true
        schema:
          $ref: '#/definitions/model.ExchangeRateReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: exchange rates
      tags:
      - exchange
  /persons/filter/currency/:currency:
    get:
      consumes:
      - application/json
      description: this endpoint converts currencies that are not in USD to USD with
        the balance converted
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: filterByCurrency
      tags:
      - person
  /persons/filter/currency/group:
    get:
      consumes:
      - application/json
      description: this endpoint groups persons by currency
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: groupByCurrency
      tags:
      - person
schemes:
- https
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
